### ISSUE TITLE
Phone Model values is null while injecting the data

### ISSUE THREAD

**Issue by gstephin** [checkout/frames-android#49]
In the case of injecting the billing details, if the user needs need to edit the details and clicked on navigation button causes null pointer exception in Phone Model    

    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String 
     com.checkout.android_sdk.Models.PhoneModel.getCountry_code()' on a null object reference
        at com.checkout.android_sdk.View.BillingDetailsView$9.onClick(BillingDetailsView.java:280)
        at android.view.View.performClick(View.java:7265)
        at android.view.View.performClickInternal(View.java:7221)
        at android.view.View.access$3800(View.java:836)
        at android.view.View$PerformClick.run(View.java:27927)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7802)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)

**Comment by shavinda-rabichandran-cko** [comment]
@gstephin Thank you for reporting this bug. We are investigating this at present and will include a fix in the next scheduled release.

**Comment by gstephin** [comment]
@shavinda-rabichandran-cko Also can you ignore the javascript errors while loading the success and failure urls in 3DS  method.  https://stackoverflow.com/questions/32530228/android-api-23-webview-how-to-ignore-javascript-errors
